### ISSUE TITLE
Improve how the generators are loaded

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-parser#1]
I want to create a brand new generator without modifying catbuffer-generators but it's failing. 

````
usage: python -m catbuffer_parser [-h] -s SCHEMA [-o OUTPUT] [-i INCLUDE] [-g {}] [-c COPYRIGHT]
python -m catbuffer_parser: error: argument -g/--generator: invalid choice: 'my-custom-generator' (choose from )
````

Atm, this tool is not clear how a new generator can be executed. I know you need to provide an All.py file with the generator in a map but this is not dev-friendly. Also, the exception is not logged anywhere so it's not clear why the All.py is not loaded leaving the map empty. 

https://github.com/nemtech/catbuffer-parser/blob/main/catbuffer_parser/__main__.py#L10

This issue is to 
1) Improve the exception handling
2) Allow devs to provide a custom generator class without the All.py, like `--generator-class myCustomGenerator.MustCustomFileGenerator` if this is possible

**Comment by Jaguar0625** [comment]
Fixed in eb123ad61016069006185f6bb10a0806420776c5.
