### ISSUE TITLE
Consider simplifying yaml output types

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-parser#26]
Instead of this:

  - comments: proof data
    disposition: array
    element_disposition:
      signedness: unsigned
      size: 1
    name: proof
    size: proof_size
    **type: byte**

Consider doing something like this instead:

  - comments: proof data
    disposition: array
    name: proof
    size: proof_size
    **type: uint8**

or even better: 

  - comments: proof data
    name: proof
    size: proof_size
    **type: array uint8**

**Comment by Momo10101** [comment]
I think we could simplify this even more by getting rid of disposition altogether. So instead of:

```
disposition: const
disposition: inline
disposition: array_sized
```

we could just do

```
type: const uint8
type: inline EntityBody
type: array_sized EmbeddedTransaction
```

etc..

**Comment by Jaguar0625** [comment]
using AST you can access FixedSizeInteger.short_name and get `uint8`. dropping disposition doesn't seem like a good idea as it would lead to a lot of duplication.
