### ISSUE TITLE
"element_disposition" for some fields has an unknown value of "id001" 

### ISSUE THREAD

**Issue by Momo10101** [symbol/catbuffer-parser#27]
When parsing the NEM schemas some fields produce the following YAML output

```
  - comments: new namespace name
    disposition: array
    element_disposition: *id001
    name: name
    size: name_size
    type: byte
```

"*id001" is a bug

**Comment by Jaguar0625** [comment]
this is due to an optimization in the python yaml.dumps. however, the yaml checked into the catapult-schemas no longer has any of these references.
